# Generated by Django 5.1.1 on 2024-10-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_du_produit', models.CharField(max_length=120)),
                ('Description_du_produit', models.TextField()),
                ('Quantité_actuelle_en_stock', models.IntegerField(max_length=1000)),
                ('Seuil_minimum_en_stock', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
